### ISSUE TITLE
Repo is not tested

### ISSUE THREAD

**Issue by rjw57** [uisautomation/django-boilerplate#12]
Ideally we should have some way to test this template in Travis. (Create new project, run migration, tox, etc. on it.) We can't do this now because the entire directory is a template and the boilerplate Travis configuration would be clobbered. It would be nice to find a solution to this.

**Comment by abrahammartin** [comment]
I presume you could do a dockerfile that adds the repo into it and executes django-admin using the local directory as the template.

`django-admin startapp --template=/Users/jezdez/Code/my_app_template myapp`

[https://docs.djangoproject.com/en/2.0/ref/django-admin/#cmdoption-startapp-template](url)

**Comment by abrahammartin** [comment]
it will also fail on trying to test admin via lookup
